"""
Voxora Backend — Conversation and Message models.

Conversations store the full chat history with context for follow-up questions.
"""

import uuid

from sqlalchemy import ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDMixin


class Conversation(Base, UUIDMixin, TimestampMixin):
    """A conversation session between a user and Voxora."""

    __tablename__ = "conversations"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False, index=True
    )
    title: Mapped[str | None] = mapped_column(String(500), nullable=True)
    context_stack: Mapped[dict] = mapped_column(
        JSONB, default=dict, server_default="{}"
    )
    status: Mapped[str] = mapped_column(
        String(20), default="active", server_default="active"
    )  # "active", "archived"

    # Relationships
    user = relationship("User", back_populates="conversations")
    messages = relationship(
        "Message", back_populates="conversation", lazy="selectin",
        order_by="Message.created_at"
    )

    def __repr__(self) -> str:
        return f"<Conversation {self.id} user={self.user_id}>"


class Message(Base, UUIDMixin, TimestampMixin):
    """A single message in a conversation (user question or AI response)."""

    __tablename__ = "messages"

    conversation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("conversations.id", ondelete="CASCADE"), nullable=False, index=True
    )
    role: Mapped[str] = mapped_column(
        String(20), nullable=False
    )  # "user", "assistant", "system"
    content: Mapped[str] = mapped_column(Text, nullable=False)
    input_mode: Mapped[str] = mapped_column(
        String(10), default="text"
    )  # "text", "voice"

    # AI-parsed data
    intent: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    entities: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    metadata_extra: Mapped[dict | None] = mapped_column(
        "metadata", JSONB, nullable=True
    )

    # Relationships
    conversation = relationship("Conversation", back_populates="messages")
    visualizations = relationship("Visualization", back_populates="message", lazy="selectin")
    query_logs = relationship("QueryLog", back_populates="message", lazy="noload")

    def __repr__(self) -> str:
        return f"<Message {self.role}: {self.content[:50]}>"


class Visualization(Base, UUIDMixin, TimestampMixin):
    """A chart or visualization generated for a message response."""

    __tablename__ = "visualizations"

    message_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("messages.id", ondelete="CASCADE"), nullable=False, index=True
    )
    chart_type: Mapped[str] = mapped_column(
        String(30), nullable=False
    )  # "bar", "line", "pie", "table", "kpi", "map"
    chart_config: Mapped[dict] = mapped_column(JSONB, default=dict, server_default="{}")
    data_payload: Mapped[dict] = mapped_column(JSONB, default=dict, server_default="{}")
    title: Mapped[str | None] = mapped_column(String(500), nullable=True)

    # Relationships
    message = relationship("Message", back_populates="visualizations")

    def __repr__(self) -> str:
        return f"<Visualization {self.chart_type}: {self.title}>"


class QueryLog(Base, UUIDMixin, TimestampMixin):
    """Audit log of BigQuery queries generated by Voxora."""

    __tablename__ = "query_logs"

    message_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("messages.id", ondelete="CASCADE"), nullable=False, index=True
    )
    generated_sql: Mapped[str] = mapped_column(Text, nullable=False)
    sanitized_sql: Mapped[str | None] = mapped_column(Text, nullable=True)
    execution_time_ms: Mapped[float | None] = mapped_column(nullable=True)
    rows_returned: Mapped[int | None] = mapped_column(nullable=True)
    status: Mapped[str] = mapped_column(
        String(20), default="success"
    )  # "success", "error", "timeout"
    bigquery_job_info: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # Relationships
    message = relationship("Message", back_populates="query_logs")

    def __repr__(self) -> str:
        return f"<QueryLog status={self.status} rows={self.rows_returned}>"
